CHANGELOG.md, react/components/LoginAsCustomer.js, react/components/Popover.js, react/index.js
Fix alignment and changed bar height
Move visual appealing interface
[workspace](https://felipe--storecomponents.myvtex.com)
=> Fix alignment and changed bar height

CHANGELOG.md, react/index.js
Fix bug when impersonate is called and it fails
Fix refetch loop when impersonate
[workspace](https://felipe--storecomponents.myvtex.com/)
=> Fix refetch loop when impersonate

.eslintrc, CHANGELOG.md, manifest.json
Remove unnecessary dependencies.
https://bruno--storecomponents.myvtex.com/
Impersonate contato@diasbruno.com user
=> Update dependencies of sessions

CHANGELOG.md, manifest.json, react/index.js, react/utils/processSession.js, react/utils/propTypes.js
Fix Error on processSession when the profile wasn´t  present
Component breaking
[work](https://felipe1--storecomponents.myvtex.com/)
=> Yet another telemarketing fix :'/

CHANGELOG.md, react/index.js
Removing loading component
https://cartabranca--storecomponents.myvtex.com
=> Removing loading component

CHANGELOG.md, react/icons/CustomerIcon.js, react/icons/TelemarketingIcon.js
Use dreamstore icon pack.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/d?map=c%2Cc&rest=Smartphones).
=> Use dreamstore icon pack

CHANGELOG.md, manifest.json, react/components/LoginAsCustomer.js, react/components/LogoutCustomerSession.js, react/components/Popover.js, react/components/Telemarketing.js, react/global.css
Replace tachyons colors/typography and CSS colors with design tokens
Make style more customizable
[Access this workspace](https://theoworkspace--storecomponents.myvtex.com/)
=> Refact to use design tokens

CHANGELOG.md, manifest.json, react/components/LogoutCustomerSession.js, react/components/Popover.js, react/components/Telemarketing.js, react/global.css
Fix design issues on telemarketing popover and bar
Issues related to popover and bar on web and mobile layouts
[Access this workspace](https://theo--storecomponents.myvtex.com/)
=> Fix design issues on telemarketing

CHANGELOG.md, manifest.json, react/components/LoginAsCustomer.tsx, react/components/LogoutCustomerSession.tsx, react/components/Telemarketing.tsx, react/package.json, react/yarn.lock
https://next--storecomponents.myvtex.com/
=> Update telemarketing icon

CHANGELOG.md, manifest.json, react/components/LoginAsCustomer.tsx, react/components/LogoutCustomerSession.tsx, react/components/Popover.tsx, react/components/Telemarketing.tsx, react/index.tsx, react/telemarketing.css
As title says
[Access this workspace](https://headercss--storecomponents.myvtex.com/)
=> Suport to css modules

CHANGELOG.md, manifest.json, react/telemarketing.css
Create default classes to avoid appear `undefined` class in the DOM elements.
[Click here to access the workspace.](https://waza3--storecomponents.myvtex.com/)
=> Remove undefined class

CHANGELOG.md, manifest.json, react/components/Telemarketing.tsx, react/typings/render.d.ts, react/typings/vtex.store-components.d.ts, react/typings/vtex.use-svg.d.ts
As the title says
https://padding--storecomponents.myvtex.com/
=> Add Container for adjusting search result to store padding

CHANGELOG.md, manifest.json, react/tsconfig.json, store/blocks.json, store/interfaces.json
As the title says
https://tele--storecomponents.myvtex.com/st-tropez-shorts/p
=> Fix wrong declarations of interfaces and blocks

CHANGELOG.md, manifest.json
=> Release v2.6.2

CHANGELOG.md, manifest.json, react/components/LoginAsCustomer.tsx, react/components/LogoutCustomerSession.tsx, react/components/Telemarketing.tsx, react/typings/vtex.dreamstore-icons.d.ts, react/typings/vtex.use-svg.d.ts
As the title says
Related with: 
https://bruno--storecomponents.myvtex.com/
=> Now, icons are import from vtex.dreamstore-icons

CHANGELOG.md, manifest.json
=> Release v2.7.2

CHANGELOG.md, react/__mocks__/vtex.styleguide.tsx, react/__tests__/Telemarketing.test.tsx, react/__tests__/__snapshots__/Telemarketing.test.tsx.snap
=> Upgrade test suite adding more tests

react/__mocks__/vtex.render-runtime.tsx, react/__mocks__/vtex.store-components.tsx, react/__mocks__/vtex.store-icons.tsx, react/__mocks__/vtex.styleguide.tsx, react/__tests__/Telemarketing.test.tsx, react/__tests__/__snapshots__/Telemarketing.test.tsx.snap, react/package.json, react/tsconfig.json, react/yarn.lock
Update tests infrastructure.
Make it more easy to test and avoid testing implementation details.
Just run `yarn test` inside `react/`
=> Change tests to @vtex/test-tools

CHANGELOG.md, manifest.json, react/index.tsx
As the title says.
Linked @ [workspace](https://firefoxtlmkt--storecomponents.myvtex.com/)
=> Fix infinite loop due useCallback wrong dependency

CHANGELOG.md, manifest.json, react/__tests__/__snapshots__/Telemarketing.test.tsx.snap, react/components/Telemarketing.tsx
Add w-100 to the telemarketing header again
=> Fix/w-100: The Return

CHANGELOG.md, manifest.json, react/__tests__/__snapshots__/Telemarketing.test.tsx.snap, react/components/LoginAsCustomer.tsx, react/components/Popover.tsx
As the title says.
Linked @ [workspace](https://teletokens--storecomponents.myvtex.com/)
=> Using tokens to define responsive width

.gitignore, .travis.yml, .vtexignore, README.md, react/package.json, react/yarn.lock
=> Add tests coverage with Coveralls

CHANGELOG.md, manifest.json, react/tsconfig.json
Makes build to pass in new React 3.x builder
Build not passing in new React 3.x builder
=> Makes build to pass in new React 3.x builder

CHANGELOG.md, manifest.json, messages/context.json, messages/en.json, messages/es.json, messages/pt.json, react/components/LoginAsCustomer.tsx, react/components/LogoutCustomerSession.tsx, react/components/Telemarketing.tsx
=> Scope Messages

CHANGELOG.md, store/interfaces.json
I think there is no need to load telemarketing synchronously in store
=> Adds lazy load to telemarketing

CHANGELOG.md, docs/README.md, manifest.json, react/__mocks__/vtex.css-handles.tsx, react/__tests__/__snapshots__/Telemarketing.test.tsx.snap, react/components/LoginAsCustomer.tsx, react/components/LogoutCustomerSession.tsx, react/components/Telemarketing.tsx, react/typings/vtex.css-handles.d.ts
As the title says
[Workspace](https://iarontelevendas--storecomponents.myvtex.com/)
login with a telemarketing account
=> Update CSS handles

CHANGELOG.md, react/components/TelemarketingContainer.tsx, react/typings/vtex.store-resources.d.ts
https://fidelis--storecomponents.myvtex.com/everyday-necessaire/p
=> import session query directly

CHANGELOG.md, messages/ar-SA.json, messages/no-NO.json
Add Arabic and Norwegian translation
=> Add Arabic and Norwegian translation

CHANGELOG.md, messages/ar-SA.json
=> Fixed Arabic translation

CHANGELOG.md, messages/id-ID.json
Add Indonesian translation. Tracked by task [LOC-9012](https://vtex-dev.atlassian.net/browse/LOC-9012).
=> Add Indonesian translation
